Repository treecreate/webstore, pull requests merged in 2021-09, with the labels that each got.

#95 Feat/#77 implement newsletter signup
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/Newsletter.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/NewsletterController.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/NewsletterRepository.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/dto/GetNewslettersResponse.java
  apps/api/src/test/java/dk/treecreate/api/newsletter/NewsletterControllerTests.java
  apps/webstore/src/app/shared/services/newsletter/newsletter.service.spec.ts
  apps/webstore/src/app/shared/services/newsletter/newsletter.service.ts
  libs/interfaces/src/lib/index.ts
  libs/interfaces/src/lib/newsletter/index.ts
  libs/interfaces/src/lib/newsletter/newsletter.dto.ts
  libs/interfaces/src/lib/newsletter/newsletter.interface.ts
Labels: feat 🎸

#97 Test/#79 Add e2e tests for login and signup
  apps/webstore-e2e/src/integration/components/navbar.spec.ts
  apps/webstore-e2e/src/integration/pages/login/login.spec.ts
  apps/webstore-e2e/src/integration/pages/signup/signup.spec.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  jest.config.js
  libs/mocks/.eslintrc.json
  libs/mocks/README.md
  libs/mocks/jest.config.js
  libs/mocks/src/index.ts
  libs/mocks/src/lib/authentication/auth-user.enum.ts
  libs/mocks/src/lib/authentication/auth-user.mock.ts
  libs/mocks/src/lib/authentication/authentication.service.ts
  libs/mocks/src/lib/authentication/index.ts
  libs/mocks/src/test-setup.ts
  libs/mocks/tsconfig.json
  libs/mocks/tsconfig.lib.json
  libs/mocks/tsconfig.spec.json
  nx.json
  package-lock.json
  tsconfig.base.json
  workspace.json
Labels: test 💍

#98 Feat/#96 localize the whole page
  apps/webstore-e2e/src/integration/components/navbar.spec.ts
  apps/webstore-e2e/src/integration/pages/login/login.spec.ts
  apps/webstore-e2e/src/integration/pages/signup/signup.spec.ts
  apps/webstore-e2e/src/integration/services/localization/localization.spec.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/collection/collection.component.html
  apps/webstore/src/app/pages/auth/login/login.component.html
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.css
  apps/webstore/src/app/pages/auth/profile/profile.component.html
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/verification/verification.component.html
  apps/webstore/src/app/pages/home/carousel/carousel.component.html
  apps/webstore/src/app/pages/home/carousel/carousel.component.ts
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.html
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.html
  apps/webstore/src/app/pages/payment-success/payment-success.component.html
  apps/webstore/src/app/pages/product/not-signed-in/not-signed-in.component.html
  apps/webstore/src/app/shared/components/footer/footer.component.html
  apps/webstore/src/app/shared/components/info-popover/info-popover.component.html
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.html
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.spec.ts
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.ts
  apps/webstore/src/app/shared/components/items/checkout-item/checkout-item.component.html
  apps/webstore/src/app/shared/components/items/design-item/design-item.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.html
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/privacy-notice-modal/privacy-notice-modal.component.html
  apps/webstore/src/app/shared/components/modals/terms-of-sale-modal/terms-of-sale-modal.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.css
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.css
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.html
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.spec.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.ts
  apps/webstore/src/app/shared/services/newsletter/newsletter.service.ts
  apps/webstore/src/assets/icons/globe.svg
  apps/webstore/src/i18n/messages.dk.xlf
  apps/webstore/src/i18n/messages.xlf
  apps/webstore/src/styles.css
Labels: medium priority

#104 Feat/#103 add update password
  apps/webstore-e2e/src/integration/pages/profile/profile.spec.ts
  apps/webstore-e2e/src/integration/pages/unsubscribe/unsubscribe.spec.ts
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.html
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.css
  apps/webstore/src/app/pages/auth/profile/profile.component.html
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.css
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.html
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.spec.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/auth/verification/verification.component.ts
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.css
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.css
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.html
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.html
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.css
  apps/webstore/src/app/shared/services/user/user.service.ts
  apps/webstore/src/app/shared/services/verify/verify.service.ts
  apps/webstore/src/assets/icons/cookies-brown-icon.png
  apps/webstore/src/assets/icons/cookies-brown-icon.svg
  apps/webstore/src/assets/icons/error-icon.svg
  apps/webstore/src/assets/icons/success-white-icon.svg
  apps/webstore/src/i18n/messages.dk.xlf
  apps/webstore/src/i18n/messages.xlf
  apps/webstore/src/index.html
  apps/webstore/src/styles.css
  workspace.json
Labels: feat 🎸

#107 Refactor/#106 styling for disabled buttons
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/basket/basket.component.spec.ts
  apps/webstore/src/styles.css
Labels: refactor 💡
