Repository treecreate/webstore, pull requests merged in 2021-03, with the labels that each got.

#30 chore: 🤖Upgrade workspace to nx 11.4.0
  migrations.json
  package-lock.json
  package.json
Labels: chore 🤖

#36 feat/#22 add google analytics
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/google-analytics/google-analytics.service.spec.ts
  apps/webstore/src/app/google-analytics/google-analytics.service.ts
  apps/webstore/src/index.html
  docs/google-analytics.md
Labels: feat 🎸

#37 feat: 🎸 Implement swagger UI documentation
  README.md
  apps/api/pom.xml
  apps/api/src/main/java/dk/treecreate/api/ApiApplication.java
  apps/api/src/main/java/dk/treecreate/api/config/SpringFoxConfig.java
  apps/api/src/main/java/dk/treecreate/api/docs/DocsController.java
  docs/swagger-ui.md
Labels: docs ✏️, feat 🎸

#44 Feat/#34 implement local storage
  apps/webstore/src/app/i18n/index.ts
  apps/webstore/src/app/i18n/locale.constants.ts
  apps/webstore/src/app/services/local-storage/index.ts
  apps/webstore/src/app/services/local-storage/local-storage.constants.ts
  apps/webstore/src/app/services/local-storage/local-storage.service.spec.ts
  apps/webstore/src/app/services/local-storage/local-storage.service.ts
  package-lock.json
  package.json
Labels: feat 🎸
