Repository treecreate/webstore, pull requests merged in 2021-04, with the labels that each got.

#48 fix: 🐛 Add credentials to the API test application.properties
  apps/api/src/test/resources/application.properties
Labels: fix 🐛

#38 🐛 feat/#18 implement a health check endpoint 🐛
  apps/api/src/main/java/dk/treecreate/api/exceptionhandling/ResourceNotFoundException.java
  apps/api/src/main/java/dk/treecreate/api/healthcheck/HealthcheckController.java
  apps/api/src/main/java/dk/treecreate/api/healthcheck/HealthcheckDto.java
  apps/api/src/main/resources/application.properties
  apps/api/src/test/java/dk/treecreate/api/exceptionhandling/RestResponseEntityExceptionHandlerTests.java
  apps/api/src/test/java/dk/treecreate/api/healthcheck/HealthcheckTests.java
  apps/api/src/test/resources/application.properties
Labels: feat 🎸, low priority

#49 Feat/#17 implement email service
  apps/api/pom.xml
  apps/api/src/main/java/dk/treecreate/api/config/LocaleConfig.java
  apps/api/src/main/java/dk/treecreate/api/config/MailConfig.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailController.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailDomain.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailTemplate.java
  apps/api/src/main/java/dk/treecreate/api/mail/dto/ResetPasswordDto.java
  apps/api/src/main/java/dk/treecreate/api/mail/dto/SignupDto.java
  apps/api/src/main/resources/application.properties
  apps/api/src/main/resources/messages.properties
  apps/api/src/main/resources/messages_dk.properties
  apps/api/src/main/resources/templates/emails/reset-password.html
  apps/api/src/main/resources/templates/emails/signup.html
  apps/api/src/test/java/dk/treecreate/api/mail/MailControllerTest.java
  apps/api/src/test/java/dk/treecreate/api/mail/MailServiceTest.java
  apps/api/src/test/resources/application.properties
Labels: feat 🎸

#50 Style/#42 change project formatting settings
  .editorconfig
  apps/api/src/main/java/dk/treecreate/api/ApiApplication.java
  apps/api/src/main/java/dk/treecreate/api/config/LocaleConfig.java
  apps/api/src/main/java/dk/treecreate/api/config/MailConfig.java
  apps/api/src/main/java/dk/treecreate/api/config/SpringFoxConfig.java
  apps/api/src/main/java/dk/treecreate/api/docs/DocsController.java
  apps/api/src/main/java/dk/treecreate/api/exceptionhandling/ResourceNotFoundException.java
  apps/api/src/main/java/dk/treecreate/api/healthcheck/HealthcheckController.java
  apps/api/src/main/java/dk/treecreate/api/healthcheck/HealthcheckDto.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailController.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailDomain.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailTemplate.java
  apps/api/src/main/java/dk/treecreate/api/mail/dto/ResetPasswordDto.java
  apps/api/src/main/java/dk/treecreate/api/mail/dto/SignupDto.java
  apps/api/src/main/resources/templates/emails/reset-password.html
  apps/api/src/main/resources/templates/emails/signup.html
  apps/api/src/test/java/dk/treecreate/api/ApiApplicationTests.java
  apps/api/src/test/java/dk/treecreate/api/exceptionhandling/ExceptionController.java
  apps/api/src/test/java/dk/treecreate/api/exceptionhandling/RestResponseEntityExceptionHandlerTests.java
  apps/api/src/test/java/dk/treecreate/api/healthcheck/HealthcheckTests.java
  apps/api/src/test/java/dk/treecreate/api/mail/MailControllerTest.java
  apps/api/src/test/java/dk/treecreate/api/mail/MailServiceTest.java
  apps/webstore-e2e/src/integration/pages/home/home.spec.ts
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.html
  apps/webstore/src/app/shared/components/footer/footer.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/index.html
  package-lock.json
Labels: style 💄

#59 Chore/#57 upgrade workspace to nx v12.0.7
  .eslintrc.json
  apps/webstore-e2e/.eslintrc.json
  apps/webstore-e2e/src/integration/components/cookie-prompt.spec.ts
  apps/webstore-e2e/src/integration/components/footer.spec.ts
  apps/webstore-e2e/src/integration/components/privacy-notice.spec.ts
  apps/webstore-e2e/src/integration/components/terms-of-sale.spec.ts
  apps/webstore-e2e/src/integration/components/terms-of-use.spec.ts
  apps/webstore-e2e/src/integration/pages/page-not-found/page-not-found.spec.ts
  apps/webstore-e2e/src/integration/services/localization/localization.spec.ts
  apps/webstore-e2e/src/support/commands.ts
  apps/webstore-e2e/tslint.json
  apps/webstore/.eslintrc.json
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.ts
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/modals/privacy-notice-modal/privacy-notice-modal.component.ts
  apps/webstore/src/app/shared/components/modals/terms-of-sale-modal/terms-of-sale-modal.component.ts
  apps/webstore/src/app/shared/components/modals/terms-of-use-modal/terms-of-use-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.spec.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/guards/cookie-guard/cookie.guard.ts
  apps/webstore/src/app/shared/services/google-analytics/google-analytics.service.ts
  apps/webstore/tslint.json
  libs/models/.eslintrc.json
  migrations.json
  nx.json
  package-lock.json
  package.json
  tslint.json
  workspace.json
Labels: chore 🤖, low priority

#60 ci: 🎡 Add a e2e testing workflow for CI
  .github/workflows/e2e.yml
  apps/webstore-e2e/cypress.json
Labels: ci 🎡, low priority
