Repository treecreate/webstore, pull requests merged in 2021-11, with the labels that each got.

#185 Refactor/#184 remove obsolete console logs
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
Labels: refactor 💡

#182 Feat/#123 create orders page
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderRepository.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/GetAllOrdersResponse.java
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.css
  apps/webstore/src/app/pages/auth/orders/orders.component.html
  apps/webstore/src/app/pages/auth/orders/orders.component.spec.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.scss
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.css
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/family-tree-intro-modal/family-tree-intro-modal.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.css
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.html
  apps/webstore/src/app/shared/services/order/order.service.ts
  apps/webstore/src/assets/icons/eye-white-icon.svg
  apps/webstore/src/i18n/messages.dk.xlf
  apps/webstore/src/i18n/messages.xlf
  libs/interfaces/src/lib/order/order.interface.ts
Labels: bug, feat 🎸, medium priority

#211 Chore/#tc-37 create pull request template
  .github/pull_request_template.md
  .github/workflows/ci-tests.yml
  .github/workflows/e2e.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  nx.json
  package-lock.json
  tsconfig.base.json
  workspace.json
Labels: chore 🤖

#209 Feat/#tc-16 initialize admin page
  apps/admin-page-e2e/.eslintrc.json
  apps/admin-page-e2e/cypress.json
  apps/admin-page-e2e/src/fixtures/example.json
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page-e2e/src/plugins/index.js
  apps/admin-page-e2e/src/support/app.po.ts
  apps/admin-page-e2e/src/support/commands.ts
  apps/admin-page-e2e/src/support/index.ts
  apps/admin-page-e2e/tsconfig.e2e.json
  apps/admin-page-e2e/tsconfig.json
  apps/admin-page/.browserslistrc
  apps/admin-page/.eslintrc.json
  apps/admin-page/jest.config.js
  apps/admin-page/proxy.conf.json
  apps/admin-page/src/app/app.component.css
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.component.spec.ts
  apps/admin-page/src/app/app.component.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/assets/.gitkeep
  apps/admin-page/src/environments/environment.prod.ts
  apps/admin-page/src/environments/environment.ts
  apps/admin-page/src/environments/ienvironment.ts
  apps/admin-page/src/favicon.ico
  apps/admin-page/src/index.html
  apps/admin-page/src/main.ts
  apps/admin-page/src/polyfills.ts
  apps/admin-page/src/styles.css
  apps/admin-page/src/test-setup.ts
  apps/admin-page/tsconfig.app.json
  apps/admin-page/tsconfig.editor.json
  apps/admin-page/tsconfig.json
  apps/admin-page/tsconfig.spec.json
  apps/webstore-e2e/src/integration/pages/auth/collection/collection.spec.ts
  jest.config.js
  nx.json
  package-lock.json
  package.json
  workspace.json
Labels: feat 🎸

#212 Feat/#tc-23 setup local storage
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.ts
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.ts
  apps/webstore/src/app/shared/components/toast/toast-service.ts
  apps/webstore/src/app/shared/guards/cookie-guard/cookie.guard.ts
  apps/webstore/src/app/shared/helpers/auth.interceptor.ts
  apps/webstore/src/app/shared/services/authentication/auth.service.ts
  apps/webstore/src/app/shared/services/local-storage/local-storage.service.spec.ts
  apps/webstore/src/app/shared/services/user/user.service.ts
  apps/webstore/src/app/shared/services/verify/verify.service.ts
  jest.config.js
  libs/local-storage/.babelrc
  libs/local-storage/.eslintrc.json
  libs/local-storage/README.md
  libs/local-storage/jest.config.js
  libs/local-storage/src/index.ts
  libs/local-storage/src/lib/index.ts
  libs/local-storage/src/lib/local-storage.service.ts
  libs/local-storage/tsconfig.json
  libs/local-storage/tsconfig.lib.json
  libs/local-storage/tsconfig.spec.json
  nx.json
  tsconfig.base.json
  workspace.json
Labels: feat 🎸

#214 Feat/#72 remove ability to register as any role
  apps/api/src/main/java/dk/treecreate/api/authentication/AuthController.java
  apps/api/src/main/java/dk/treecreate/api/authentication/dto/request/SignupRequest.java
  apps/api/src/test/java/dk/treecreate/api/authentication/AuthControllerTests.java
Labels: feat 🎸, high priority

#215 Feat/#tc-33 setup ng zorro
  .editorconfig
  .eslintrc.json
  .prettierrc
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page/.eslintrc.json
  apps/admin-page/jest.config.js
  apps/admin-page/src/app/app.component.css
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.component.spec.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/nz-modules.constant.ts
  apps/admin-page/src/test-setup.ts
  apps/webstore-e2e/src/integration/pages/auth/collection/collection.spec.ts
  apps/webstore/jest.config.js
  apps/webstore/src/app/app.component.html
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.html
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.ts
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.ts
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.ts
  apps/webstore/src/app/shared/components/toast/toast-service.ts
  apps/webstore/src/app/shared/guards/cookie-guard/cookie.guard.ts
  apps/webstore/src/app/shared/helpers/auth.interceptor.ts
  apps/webstore/src/app/shared/services/authentication/auth.service.ts
  apps/webstore/src/app/shared/services/user/user.service.ts
  apps/webstore/src/app/shared/services/verify/verify.service.ts
  apps/webstore/src/test-setup.ts
  jest.config.js
  libs/assets/jest.config.js
  libs/interfaces/jest.config.js
  libs/interfaces/src/lib/order/order.interface.ts
  libs/interfaces/src/lib/pricing/discount.interface.ts
  libs/local-storage/src/lib/local-storage.service.ts
  libs/local-storage/tsconfig.spec.json
  libs/mocks/.eslintrc.json
  libs/mocks/jest.config.js
  libs/mocks/src/test-setup.ts
  libs/models/jest.config.js
  migrations.json
  nx.json
  package-lock.json
  package.json
  tsconfig.base.json
  workspace.json
Labels: feat 🎸

#217 Feat/#169 purchase without login
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/TransactionItemController.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/dto/CreateBulkTransactionItemRequest.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/dto/CreateBulkTransactionItemsRequest.java
  apps/api/src/main/java/dk/treecreate/api/utils/StringService.java
  apps/api/src/main/resources/templates/emails/order-confirmation.html
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/checkout/checkout.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/collection/collection.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/profile/profile.spec.ts
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.html
  apps/webstore/src/app/pages/auth/profile/profile.component.spec.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/auth/verification/verification.component.css
  apps/webstore/src/app/pages/auth/verification/verification.component.html
  apps/webstore/src/app/pages/auth/verification/verification.component.spec.ts
  apps/webstore/src/app/pages/auth/verification/verification.component.ts
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.spec.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-checkout-item/family-tree-checkout-item.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.ts
  apps/webstore/src/app/shared/services/order/newsletter/newsletter.service.spec.ts
  apps/webstore/src/app/shared/services/order/newsletter/newsletter.service.ts
  apps/webstore/src/app/shared/services/transaction-item/transaction-item.service.ts
  apps/webstore/src/app/shared/services/verify/verify.service.spec.ts
  apps/webstore/src/app/shared/services/verify/verify.service.ts
  libs/interfaces/src/lib/auth/login.interface.ts
  libs/interfaces/src/lib/auth/register.interface.ts
  libs/interfaces/src/lib/transaction-item/transaction-item.dto.ts
  libs/interfaces/src/lib/transaction-item/transaction-item.interface.ts
  libs/interfaces/src/lib/user/index.ts
  libs/interfaces/src/lib/user/user.interface.ts
  libs/interfaces/src/lib/user/verification.interface.ts
  libs/mocks/src/lib/authentication/auth-user.enum.ts
  libs/mocks/src/lib/authentication/auth-user.mock.ts
  libs/mocks/src/lib/authentication/authentication.service.ts
  libs/models/src/lib/local-storage/local-storage.constants.ts
Labels: bug, feat 🎸, fix 🐛, refactor 💡, style 💄, test 💍, high priority

#220 Chore/#tc 13 add dockerfile for admin page
  .deploy/admin-page/Dockerfile
  .deploy/admin-page/nginx.conf
Labels: Docker

#219 test: 💍 Add tests for orders page
  apps/webstore-e2e/src/integration/pages/auth/orders/orders.spec.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.html
  apps/webstore/src/app/pages/auth/orders/orders.component.ts
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
Labels: test 💍

#224 fix: 🐛Fix banner not showing on firefox
  apps/webstore/src/app/pages/product/product.component.scss
  libs/assets/src/lib/family-tree/banner/banner1.svg
Labels: fix 🐛

#227 Feat/#169 purchase without login
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
Labels: refactor 💡

#229 fix: 🐛 Fix banner not having the right aspect ratio
  libs/assets/src/lib/family-tree/banner/banner1.svg
Labels: fix 🐛

#230 Feat/#228 add facebook pixel for marketing
  apps/webstore/src/index.prod.html
Labels: feat 🎸

#232 fix: 🐛 Update error message for users with email in the system
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
Labels: bug

#234 refactor: 💡adjust orderId creation logic to include env
  apps/api/src/main/java/dk/treecreate/api/utils/QuickpayService.java
Labels: bug

#235 Feat/#172 add createdat updatedat to all models
  apps/api/src/main/java/dk/treecreate/api/authentication/models/Role.java
  apps/api/src/main/java/dk/treecreate/api/contactinfo/ContactInfo.java
  apps/api/src/main/java/dk/treecreate/api/designs/Design.java
  apps/api/src/main/java/dk/treecreate/api/designs/dto/UpdateDesignRequest.java
  apps/api/src/main/java/dk/treecreate/api/discount/Discount.java
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountController.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/Newsletter.java
  apps/api/src/main/java/dk/treecreate/api/order/Order.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderRepository.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/CreateOrderRequest.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/TransactionItem.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/dto/CreateTransactionItemRequest.java
  apps/api/src/main/java/dk/treecreate/api/transactionitem/dto/UpdateTransactionItemRequest.java
  apps/api/src/main/java/dk/treecreate/api/user/User.java
  apps/api/src/main/java/dk/treecreate/api/user/dto/UpdatePasswordRequest.java
  apps/api/src/main/java/dk/treecreate/api/utils/QuickpayService.java
  apps/api/src/main/java/dk/treecreate/api/utils/model/quickpay/dto/CreatePaymentLinkRequest.java
  libs/interfaces/src/lib/design/design.interface.ts
  libs/interfaces/src/lib/index.ts
  libs/interfaces/src/lib/order/order.interface.ts
  libs/interfaces/src/lib/pricing/discount.interface.ts
  libs/interfaces/src/lib/transaction-item/transaction-item.interface.ts
  libs/interfaces/src/lib/user/user.interface.ts
  libs/interfaces/src/lib/util/base.interface.ts
  libs/interfaces/src/lib/util/index.ts
Labels: feat 🎸

#249 Fix/#248 fix design miniature styling
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
Labels: bug

#246 Fix/#245 Fix discounts in no-auth page flow
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountController.java
Labels: fix 🐛

#247 fix/244 fix locale change breaking navigation
  apps/webstore/src/app/app.component.ts
Labels: bug

#253 fix: 🐛 fix discount display
  apps/api/src/main/resources/templates/emails/order-confirmation.html
Labels: bug

#255 fix: 🐛 Add meta data for facebook verification
  apps/webstore/src/index.prod.html
Labels: bug

#256 Feat/#42 migrate to angular material
  .gitignore
  apps/admin-page/jest.config.js
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/nz-modules.constant.ts
  apps/admin-page/src/index.html
  apps/admin-page/src/styles.css
  apps/webstore/jest.config.js
  libs/mocks/jest.config.js
  migrations.json
  nx.json
  package-lock.json
  package.json
  workspace.json
Labels: feat 🎸

#260 Fix/#259 fix discount applying while disabled
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
Labels: bug, test 💍

#258 Chore/#tc 22 create a population script
  apps/api/src/main/resources/application.properties
  apps/api/src/main/resources/data.sql
Labels: chore 🤖

#263 Feat/#tc 39 create page layout
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.css
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.component.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/components/temp/temp.component.css
  apps/admin-page/src/app/components/temp/temp.component.html
  apps/admin-page/src/app/components/temp/temp.component.spec.ts
  apps/admin-page/src/app/components/temp/temp.component.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/styles.css
  workspace.json
Labels: feat 🎸

#264 feat: 🎸 Update fonts in webstore
  apps/webstore-e2e/src/integration/pages/product/product.spec.ts
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/styles.css
  libs/interfaces/src/lib/design/design.interface.ts
Labels: bug, feat 🎸

#266 perf: add fixed workspace.json
  workspace.json
Labels: perf ⚡️

#269 Feat/#tc 18 create login page
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page-e2e/src/integration/login/login.spec.ts
  apps/admin-page-e2e/src/integration/page-not-found/page-not-found.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.component.spec.ts
  apps/admin-page/src/app/app.component.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/auth/auth.guard.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/dashboard/dashboard.component.css
  apps/admin-page/src/app/pages/dashboard/dashboard.component.html
  apps/admin-page/src/app/pages/dashboard/dashboard.component.spec.ts
  apps/admin-page/src/app/pages/dashboard/dashboard.component.ts
  apps/admin-page/src/app/pages/login/login.component.css
  apps/admin-page/src/app/pages/login/login.component.html
  apps/admin-page/src/app/pages/login/login.component.spec.ts
  apps/admin-page/src/app/pages/login/login.component.ts
  apps/admin-page/src/app/pages/page-not-found/page-not-found.component.css
  apps/admin-page/src/app/pages/page-not-found/page-not-found.component.html
  apps/admin-page/src/app/services/authentication/auth.service.ts
  libs/interfaces/src/lib/transaction-item/transaction-item.dto.ts
  libs/interfaces/src/lib/transaction-item/transaction-item.interface.ts
  libs/mocks/src/lib/authentication/auth-user.enum.ts
  libs/mocks/src/lib/authentication/auth-user.mock.ts
  libs/mocks/src/lib/authentication/authentication.service.ts
Labels: bug, feat 🎸, test 💍, high priority
