Repository treecreate/webstore, pull requests merged in 2021-12, with the labels that each got.

#271 Feat/#tc 26 create orders page
  apps/admin-page-e2e/src/integration/components/item-card.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.css
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/components/item-card/item-card.component.css
  apps/admin-page/src/app/components/item-card/item-card.component.html
  apps/admin-page/src/app/components/item-card/item-card.component.spec.ts
  apps/admin-page/src/app/components/item-card/item-card.component.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/login/login.component.css
  apps/admin-page/src/app/pages/login/login.component.html
  apps/admin-page/src/app/pages/orders/orders.component.css
  apps/admin-page/src/app/pages/orders/orders.component.html
  apps/admin-page/src/app/pages/orders/orders.component.spec.ts
  apps/admin-page/src/app/pages/orders/orders.component.ts
  apps/admin-page/src/app/services/orders/orders.service.spec.ts
  apps/admin-page/src/app/services/orders/orders.service.ts
  apps/admin-page/src/styles.css
Labels: feat 🎸

#272 Feat/#tc 34 automatically build and deploy docker images
  .deploy/admin-page/Dockerfile
  .deploy/api/Dockerfile
  .deploy/docker-compose.build.yml
  .deploy/docker-compose.run.yml
  .deploy/update-dev-images.sh
  .deploy/update-prod-images.sh
  .deploy/webstore/Dockerfile
  .dockerignore
  .github/workflows/build-and-deploy.yml
  .gitignore
  .vscode/settings.json
Labels: ci 🎡

#278 Feat/#tc 34 automatically build and deploy docker images
  .deploy/admin-page/Dockerfile
  .deploy/docker-compose.run.yml
  .deploy/install-docker.sh
  .deploy/login-and-update.sh
  .deploy/webstore/Dockerfile
  apps/admin-page/src/assets/env.js
  apps/admin-page/src/assets/env.template.js
  apps/admin-page/src/index.html
Labels: feat 🎸

#274 Feat/#tc 30 update order status
  .github/workflows/build-and-deploy.yml
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/orders/orders.component.css
  apps/admin-page/src/app/pages/orders/orders.component.html
  apps/admin-page/src/app/pages/orders/orders.component.ts
  apps/admin-page/src/app/services/orders/orders.service.ts
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderService.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/UpdateOrderStatusRequest.java
  apps/api/src/main/java/dk/treecreate/api/utils/model/quickpay/dto/CreatePaymentLinkRequest.java
  apps/api/src/main/resources/templates/emails/order-confirmation.html
  apps/api/src/main/resources/templates/emails/reset-password.html
  apps/api/src/main/resources/templates/emails/signup.html
  apps/api/src/main/resources/templates/emails/verify-email.html
  apps/api/src/test/java/dk/treecreate/api/authentication/AuthTestControllerTests.java
  apps/api/src/test/java/dk/treecreate/api/designs/DesignControllerTests.java
  apps/api/src/test/java/dk/treecreate/api/exceptionhandling/RestResponseEntityExceptionHandlerTests.java
  apps/api/src/test/java/dk/treecreate/api/healthcheck/HealthcheckTests.java
  apps/api/src/test/java/dk/treecreate/api/mail/MailControllerTest.java
  apps/api/src/test/java/dk/treecreate/api/order/OrderServiceTest.java
  apps/api/src/test/java/dk/treecreate/api/users/UserControllerTests.java
  apps/api/src/test/java/dk/treecreate/api/utils/LinkServiceTest.java
Labels: feat 🎸

#279 feat: TC-35 Automatically deploy to staging and prod
  .deploy/.env-files/.env.dev.api.example
  .deploy/.env-files/.env.dev.frontend.example
  .deploy/.env-files/.env.dockerhub.example
  .deploy/.env-files/.env.prod.api.example
  .deploy/.env-files/.env.prod.frontend.example
  .deploy/docker-compose.build.yml
  .deploy/login-and-update.sh
  .deploy/update-dev-images.sh
  .deploy/update-prod-images.sh
  docs/deployment-pipeline.md
Labels: docs ✏️, ci 🎡

#280 Feat/#tc 47 create account page
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page-e2e/src/integration/login/login.spec.ts
  apps/admin-page-e2e/src/integration/pages/account.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.css
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/components/change-password-dialog/change-password-dialog.component.css
  apps/admin-page/src/app/components/change-password-dialog/change-password-dialog.component.html
  apps/admin-page/src/app/components/change-password-dialog/change-password-dialog.component.spec.ts
  apps/admin-page/src/app/components/change-password-dialog/change-password-dialog.component.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/account/account.component.css
  apps/admin-page/src/app/pages/account/account.component.html
  apps/admin-page/src/app/pages/account/account.component.spec.ts
  apps/admin-page/src/app/pages/account/account.component.ts
  apps/admin-page/src/app/pages/login/login.component.ts
  apps/admin-page/src/app/services/user/user.service.spec.ts
  apps/admin-page/src/app/services/user/user.service.ts
  apps/webstore-e2e/src/integration/pages/auth/profile/profile.spec.ts
  libs/interfaces/src/lib/user/user.dto.ts
Labels: feat 🎸

#282 Feat/#tc 25 create discounts page
  apps/admin-page-e2e/src/integration/pages/discounts.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/pages/discounts/discounts.component.css
  apps/admin-page/src/app/pages/discounts/discounts.component.html
  apps/admin-page/src/app/pages/discounts/discounts.component.spec.ts
  apps/admin-page/src/app/pages/discounts/discounts.component.ts
  apps/admin-page/src/app/services/discounts/discounts.service.spec.ts
  apps/admin-page/src/app/services/discounts/discounts.service.ts
  package-lock.json
  package.json
Labels: feat 🎸

#281 Feat/#tc 49 add user param filter
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/test/java/dk/treecreate/api/order/OrderControllerTests.java
Labels: feat 🎸

#277 Feat/#tc 28 create order details page
  apps/admin-page-e2e/src/integration/pages/order-details.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/components/item-card/item-card.component.css
  apps/admin-page/src/app/components/item-card/item-card.component.html
  apps/admin-page/src/app/components/item-card/item-card.component.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/order-details/order-details.component.css
  apps/admin-page/src/app/pages/order-details/order-details.component.html
  apps/admin-page/src/app/pages/order-details/order-details.component.spec.ts
  apps/admin-page/src/app/pages/order-details/order-details.component.ts
  apps/admin-page/src/app/pages/orders/orders.component.html
  apps/admin-page/src/app/pages/orders/orders.component.ts
  apps/admin-page/src/app/services/orders/orders.service.ts
  apps/webstore-e2e/src/integration/pages/auth/orders/orders.spec.ts
  libs/interfaces/src/lib/order/order.interface.ts
Labels: feat 🎸

#289 Feat: TC 71 add active and startsAt property to discount
  apps/admin-page-e2e/src/integration/pages/discounts.spec.ts
  apps/admin-page-e2e/src/integration/pages/order-details.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/api/src/main/java/dk/treecreate/api/discount/Discount.java
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountController.java
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountService.java
  apps/api/src/main/java/dk/treecreate/api/discount/dto/CreateDiscountRequest.java
  apps/api/src/main/java/dk/treecreate/api/discount/dto/UpdateDiscountRequest.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderService.java
  apps/api/src/main/resources/application.properties
  apps/api/src/main/resources/data.sql
  apps/api/src/test/java/dk/treecreate/api/order/OrderServiceTest.java
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/checkout/checkout.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/orders/orders.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  libs/interfaces/src/lib/pricing/discount.interface.ts
Labels: feat 🎸

#286 Feat/#tc 31 add sorting to orders page
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/orders/orders.component.html
  apps/admin-page/src/app/pages/orders/orders.component.ts
Labels: feat 🎸

#287 feat: TC-48 add edit discount page
  apps/admin-page-e2e/src/integration/pages/edit-discount.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.css
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.html
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.spec.ts
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.ts
  apps/admin-page/src/app/services/discounts/discounts.service.ts
Labels: feat 🎸

#290 feat: TC-61 Update discount
  apps/admin-page-e2e/src/integration/pages/discounts.spec.ts
  apps/admin-page-e2e/src/integration/pages/edit-discount.spec.ts
  apps/admin-page-e2e/src/integration/pages/order-details.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page-e2e/src/integration/pages/users.spec.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.html
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.spec.ts
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.ts
  apps/admin-page/src/app/services/discounts/discounts.service.ts
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountService.java
  apps/api/src/main/resources/application.properties
  libs/interfaces/src/lib/pricing/discount.dto.ts
  libs/interfaces/src/lib/pricing/index.ts
  package-lock.json
  package.json
Labels: feat 🎸

#292 Feat/#tc 59 add ability to view an orders designs
  apps/admin-page/src/app/components/item-card/item-card.component.css
  apps/admin-page/src/app/pages/order-details/order-details.component.css
  apps/admin-page/src/app/pages/order-details/order-details.component.html
  apps/admin-page/src/app/pages/order-details/order-details.component.ts
  apps/admin-page/src/assets/env.js
  apps/admin-page/src/assets/env.template.js
  apps/admin-page/src/environments/environment.prod.ts
  apps/admin-page/src/environments/environment.ts
  apps/admin-page/src/environments/ienvironment.ts
Labels: feat 🎸

#293 feat: TC-63 endpoint for updating order
  apps/admin-page-e2e/src/integration/pages/edit-discount.spec.ts
  apps/admin-page-e2e/src/integration/pages/order-details.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/services/orders/orders.service.ts
  apps/api/src/main/java/dk/treecreate/api/contactinfo/dto/UpdateContactInfoRequest.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderService.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/UpdateOrderRequest.java
  apps/api/src/test/java/dk/treecreate/api/order/OrderControllerTests.java
  apps/api/src/test/java/dk/treecreate/api/order/OrderServiceTest.java
Labels: feat 🎸

#283 feat: TC-51 Intergrate Shipmndo API
  .format_configs/java-formatting.xml
  apps/admin-page/src/app/components/item-card/item-card.component.css
  apps/admin-page/src/app/pages/order-details/order-details.component.html
  apps/admin-page/src/app/pages/order-details/order-details.component.spec.ts
  apps/admin-page/src/app/pages/order-details/order-details.component.ts
  apps/admin-page/src/app/services/shipmondo/shipmondo.service.spec.ts
  apps/admin-page/src/app/services/shipmondo/shipmondo.service.ts
  apps/api/src/main/java/dk/treecreate/api/ApiApplication.java
  apps/api/src/main/java/dk/treecreate/api/config/CustomPropertiesConfig.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/ShipmentObject.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/ShipmentObjectResponse.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/ShipmondoController.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/ShipmondoService.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/dto/ShipmentInfoDto.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/BillTo.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/Cod.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/Customs.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/Dfm.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/PalletExchange.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/Parcels.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/PickUp.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/PrintAt.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/ReturnTo.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/SendLabel.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/ServicePoint.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/customs_components/Goods.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/parcels_components/DangerousGoods.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_components/parcels_components/DeclaredValue.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_response_components/BillToResponse.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_response_components/LabelResponse.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_response_components/ParcelsResponse.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/shipment_object_response_components/PickupResponse.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/temp/QuoteObject.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/utility/Address.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/utility/ContactInfo.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/utility/DateAndTime.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/utility/Receiver.java
  apps/api/src/main/java/dk/treecreate/api/shipmondo/utility/Sender.java
  apps/api/src/main/resources/application.properties
  apps/api/src/test/java/dk/treecreate/api/shipmondo/ShipmondoControllerTest.java
  libs/interfaces/src/lib/index.ts
  libs/interfaces/src/lib/shipmondo/index.ts
  libs/interfaces/src/lib/shipmondo/shipmondo-address.interface.ts
  libs/interfaces/src/lib/shipmondo/shipmondo-contact-info.interface.ts
  libs/interfaces/src/lib/shipmondo/shipmondo.dto.ts
Labels: feat 🎸
