Repository treecreate/webstore, pull requests merged in 2022-03, with the labels that each got.

#318 Fix/#tc 106 fix styling for mobile options on safari
  apps/webstore-e2e/src/integration/components/family-tree-intro-modal.spec.ts
  apps/webstore-e2e/src/integration/components/newsletter-popup-modal.spec.ts
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.mobile.scss
  apps/webstore/src/app/pages/product/product.component.scss
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.ts
  apps/webstore/src/assets/icons/pen-icon.svg
Labels: bug

#312 Refactor/#tc 108 rework draggable box text
  apps/webstore-e2e/src/integration/pages/product/product.spec.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.scss
  apps/webstore/src/app/pages/auth/checkout/checkout.component.css
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/collection/collection.component.css
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-checkout-item/family-tree-checkout-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.css
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.html
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.html
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.mobile.scss
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.scss
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
Labels: refactor 💡

#322 Feat/#tc 122 add no design background design
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
  libs/assets/src/lib/family-tree/box-design.enum.ts
  libs/assets/src/lib/family-tree/tree-design.enum.ts
  libs/assets/src/lib/family-tree/tree-design/tree4.svg
Labels: feat 🎸
