Repository treecreate/webstore, pull requests merged in 2022-10, with the labels that each got.

#396 Feat/#141 mvp dashboard
  apps/admin-page/src/app/pages/dashboard/dashboard.component.css
  apps/admin-page/src/app/pages/dashboard/dashboard.component.html
  apps/admin-page/src/app/pages/dashboard/dashboard.component.scss
  apps/admin-page/src/app/pages/dashboard/dashboard.component.spec.ts
  apps/admin-page/src/app/pages/dashboard/dashboard.component.ts
  apps/admin-page/src/app/pages/discounts/discounts.component.spec.ts
Labels: feat 🎸

#398 Fix/#247 Remove flaky e2e tests
  apps/webstore-e2e/src/integration/components/modals/template-family-tree-modal.spec.ts
Labels: fix 🐛

#399 fix/#270 Change error log url max length from 50 to 100
  apps/api/src/main/java/dk/treecreate/api/errorlog/Errorlog.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/dto/CreateErrorlogRequest.java
Labels: fix 🐛

#400 Feat/#119 create trustpilot feedback email
  .env.template
  apps/api/src/main/java/dk/treecreate/api/config/CustomPropertiesConfig.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/resources/application.properties
Labels: feat 🎸

#404 Feat/#271 upgrade mvp dasboard
  apps/admin-page/src/app/pages/dashboard/dashboard.component.html
  apps/admin-page/src/app/pages/dashboard/dashboard.component.scss
  apps/admin-page/src/app/pages/dashboard/dashboard.component.ts
Labels: feat 🎸

#401 Feat/#258 upgrade temple selection
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.html
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.html
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.html
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.scss
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
Labels: feat 🎸

#407 Feat/#277 Add extra info to logs
  apps/api/src/main/java/dk/treecreate/api/errorlog/Errorlog.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/ErrorlogController.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/dto/CreateErrorlogRequest.java
  apps/api/src/main/java/dk/treecreate/api/events/Event.java
  apps/api/src/main/java/dk/treecreate/api/events/EventController.java
  apps/api/src/main/java/dk/treecreate/api/events/dto/CreateEventRequest.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/webstore/src/app/shared/services/errorlog/errorlog.service.ts
  apps/webstore/src/app/shared/services/events/events.service.ts
  libs/interfaces/src/lib/errorlog/errorlog.interace.ts
  libs/interfaces/src/lib/events/event.interface.ts
Labels: feat 🎸

#297 Feat/#239 add payment link to order details
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/utils/QuickpayService.java
  apps/api/src/main/java/dk/treecreate/api/utils/model/quickpay/Payment.java
  apps/api/src/main/java/dk/treecreate/api/utils/model/quickpay/PaymentLink.java
  apps/api/src/main/java/dk/treecreate/api/utils/model/quickpay/dto/GetPaymentLinkResponse.java
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.ts
  apps/webstore/src/app/shared/services/order/order.service.ts
Labels: feat 🎸, low priority

#405 Feat/#256 upgrade size selection
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.scss
Labels: feat 🎸

#408 feat: 🎸 Make size selection bosses clickable
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
Labels: feat 🎸

#409 Feat/#276 log every page change
  apps/webstore-e2e/src/integration/pages/auth/login.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/signup.spec.ts
  apps/webstore/src/app/app.component.ts
Labels: feat 🎸

#412 Feat/ad optimisation
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/products/products.component.scss
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.scss
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.scss
Labels: feat 🎸

#414 refactor: 💡 Remove references to Collection and Collection page
  apps/webstore-e2e/src/integration/pages/auth/collection.spec.ts
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/collection/collection.component.css
  apps/webstore/src/app/pages/auth/collection/collection.component.html
  apps/webstore/src/app/pages/auth/collection/collection.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.html
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.css
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.html
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
  apps/webstore/src/sitemap.xml
Labels: refactor 💡

#411 Feat/#279 add more event logs
  apps/webstore/src/app/pages/about-us/about-us.component.html
  apps/webstore/src/app/pages/about-us/about-us.component.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.html
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.html
  apps/webstore/src/app/pages/auth/orders/orders.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.html
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.html
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/home/home.component.ts
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.html
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.ts
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.html
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.ts
  apps/webstore/src/app/pages/payment-success/payment-success.component.html
  apps/webstore/src/app/pages/payment-success/payment-success.component.ts
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.html
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.html
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.ts
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.html
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.ts
  apps/webstore/src/app/pages/products/products.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.html
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.html
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.ts
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.ts
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.html
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
Labels: feat 🎸

#418 Fix/#292 fix events url field
  apps/api/src/main/java/dk/treecreate/api/errorlog/Errorlog.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/dto/CreateErrorlogRequest.java
  apps/api/src/main/java/dk/treecreate/api/events/Event.java
  apps/api/src/main/java/dk/treecreate/api/events/dto/CreateEventRequest.java
  apps/webstore/src/app/shared/services/errorlog/errorlog.service.ts
  apps/webstore/src/app/shared/services/events/events.service.ts
Labels: fix 🐛

#417 Feat/#278 log where user was redirected from
  apps/webstore/src/app/app.component.ts
Labels: feat 🎸

#419 Chore/#246 integrate google tag manager
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/index.html
  apps/webstore/src/index.prod.html
Labels: feat 🎸

#421 fix: 🐛 Add missing translation for order confirmation email
  apps/api/src/main/resources/messages.properties
  apps/api/src/main/resources/messages_da.properties
  apps/api/src/main/resources/templates/emails/order-confirmation.html
Labels: fix 🐛
