Repository treecreate/webstore, pull requests merged in 2022-02, with the labels that each got.

#306 refactor: 💡 Change default family tree design for valentines
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
Labels: refactor 💡

#225 Perf/#222 improve performance of family tree
  apps/api/src/main/resources/data.sql
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.html
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.scss
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.html
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.scss
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
Labels: perf ⚡️

#307 test: 💍 Temporirly skip some product page e2e tests
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore-e2e/src/integration/pages/product/product.spec.ts
Labels: test 💍

#308 Refactor/#tc 104 move close drag btn to outside of box
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.mobile.scss
  apps/webstore/src/app/pages/product/product.component.scss
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
  libs/assets/src/lib/family-tree/box-design-1/close-button.svg
  libs/assets/src/lib/family-tree/box-options-design.enum.ts
  libs/assets/src/lib/family-tree/box-options/box-options-hidden.svg
  libs/assets/src/lib/family-tree/box-options/box-options-visible.svg
  libs/assets/src/lib/family-tree/box-options/close-button.svg
  libs/assets/src/lib/family-tree/box-options/drag-button.svg
  libs/assets/src/lib/family-tree/close-box-design.enum.ts
  libs/assets/src/lib/family-tree/index.ts
Labels: refactor 💡, style 💄

#309 Refactor/#tc 82 remove large font option
  apps/api/src/main/java/dk/treecreate/api/designs/Design.java
  apps/api/src/main/java/dk/treecreate/api/designs/dto/CreateDesignRequest.java
  apps/api/src/main/java/dk/treecreate/api/designs/dto/UpdateDesignRequest.java
  apps/api/src/main/resources/data.sql
  apps/webstore-e2e/src/integration/components/go-to-basket-modal.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/checkout/checkout.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/collection/collection.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/orders/orders.spec.ts
  apps/webstore-e2e/src/integration/pages/product/product.spec.ts
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.spec.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-miniature/family-tree-miniature.component.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/app/shared/services/design/family-tree-design.service.ts
  libs/interfaces/src/lib/design/design.interface.ts
Labels: refactor 💡

#311 Refactor/#tc 73 remove design title
  .github/workflows/build-and-deploy.yml
  apps/api/src/main/java/dk/treecreate/api/designs/Design.java
  apps/api/src/main/java/dk/treecreate/api/designs/dto/UpdateDesignRequest.java
  apps/api/src/main/resources/data.sql
  apps/api/src/main/resources/messages.properties
  apps/api/src/main/resources/messages_dk.properties
  apps/api/src/main/resources/templates/emails/order-confirmation.html
  apps/webstore-e2e/src/integration/components/go-to-basket-modal.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/basket/basket.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/checkout/checkout.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/collection/collection.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/orders/orders.spec.ts
  apps/webstore-e2e/src/integration/pages/product/product.spec.ts
  apps/webstore/src/app/pages/product/product.component.html
  apps/webstore/src/app/pages/product/product.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.spec.ts
  apps/webstore/src/app/shared/components/items/family-tree-basket-item/family-tree-basket-item.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-checkout-item/family-tree-checkout-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-checkout-item/family-tree-checkout-item.component.ts
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.html
  apps/webstore/src/app/shared/components/items/family-tree-collection-item/family-tree-collection-item.component.ts
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.html
  apps/webstore/src/app/shared/components/items/order-item/order-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.html
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/i18n/messages.dk.xlf
  apps/webstore/src/i18n/messages.xlf
  libs/interfaces/src/lib/design/design.interface.ts
Labels: refactor 💡

#313 [TC-97]Fix view design link not working when deployed
  .deploy/.env-files/.env.dev.frontend.example
  .deploy/.env-files/.env.prod.frontend.example
Labels: bug
