Repository treecreate/webstore, pull requests merged in 2022-08, with the labels that each got.

#348 Feature/#tc 146 redesign home page
  apps/webstore-e2e/src/integration/components/modals/template-family-tree-modal.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/collection/collection.component.html
  apps/webstore/src/app/pages/auth/login/login.component.html
  apps/webstore/src/app/pages/auth/orders/orders.component.html
  apps/webstore/src/app/pages/auth/profile/profile.component.html
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.html
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.html
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.html
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.html
  apps/webstore/src/app/pages/payment-success/payment-success.component.html
  apps/webstore/src/app/pages/products/product-display/product-display.component.html
  apps/webstore/src/app/pages/products/product-display/product-display.component.scss
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.html
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.html
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.scss
  apps/webstore/src/app/pages/products/products.component.html
  apps/webstore/src/app/shared/components/footer/footer.component.html
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.html
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.html
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.scss
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/templates.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/templatesExtra.ts
Labels: style 💄

#342 feat: 🎸 Fix quotable scale issue
  apps/webstore/src/app/pages/auth/basket/basket.component.scss
  apps/webstore/src/app/pages/auth/collection/collection.component.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.scss
  apps/webstore/src/app/pages/products/products-items.constant.ts
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.css
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.html
  apps/webstore/src/app/shared/components/items/store-item/store-item.component.css
  apps/webstore/src/app/shared/components/items/store-item/store-item.component.ts
  apps/webstore/src/app/shared/components/products/quotable-design/quotable-design.component.ts
  apps/webstore/src/assets/styles/tc-buttons.css
  apps/webstore/src/styles.css
Labels: bug, high priority

#344 Feat/#tc 147 Add custom order
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailTemplate.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderService.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/CreateCustomOrderRequest.java
  apps/api/src/main/resources/application.properties
  apps/api/src/main/resources/templates/emails/custom-order-request.html
  apps/api/src/test/java/dk/treecreate/api/order/OrderControllerTests.java
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/collection/collection.component.ts
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.css
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.html
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.ts
  apps/webstore/src/app/pages/products/products-items.constant.ts
  apps/webstore/src/app/pages/products/products.component.scss
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.html
  apps/webstore/src/app/shared/components/items/custom-order-display/CustomOrderExampleType.ts
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.html
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.scss
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.spec.ts
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.ts
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.html
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.scss
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.spec.ts
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.ts
  apps/webstore/src/app/shared/services/order/order.service.ts
  apps/webstore/src/assets/img/custom-order-example/custom-order-img-1.png
  apps/webstore/src/assets/img/custom-order-example/custom-order-img-2.png
  apps/webstore/src/assets/img/custom-order-example/custom-order-img-3.png
  apps/webstore/src/assets/img/custom-order-example/custom-order-img-4.png
  apps/webstore/src/assets/img/custom-order-example/custom-order-img-5.png
  apps/webstore/src/assets/img/team/Teo-TC-2022.png
  apps/webstore/src/assets/styles/tc-input-field.scss
  apps/webstore/src/i18n/messages.dk.xlf
  apps/webstore/src/i18n/messages.xlf
  libs/interfaces/src/lib/order/order.dto.ts
Labels: feat 🎸

#347 Chore/#tc 164 add error logging to webstore
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/material.constant.ts
  apps/admin-page/src/app/pages/errorlogs/errorlogs.component.css
  apps/admin-page/src/app/pages/errorlogs/errorlogs.component.html
  apps/admin-page/src/app/pages/errorlogs/errorlogs.component.ts
  apps/admin-page/src/app/services/errorlogs/errorlogs.service.ts
  apps/api/src/main/java/dk/treecreate/api/authentication/AuthController.java
  apps/api/src/main/java/dk/treecreate/api/authentication/services/AuthUserService.java
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/ErrorPriority.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/Errorlog.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/ErrorlogController.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/ErrorlogRepository.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/ErrorlogService.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/dto/CreateErrorlogRequest.java
  apps/api/src/main/java/dk/treecreate/api/errorlog/dto/GetErrorlogsResponse.java
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/collection/collection.component.spec.ts
  apps/webstore/src/app/pages/auth/collection/collection.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.spec.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.ts
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.ts
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/newsletter-signup-modal/newsletter-signup-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.spec.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.ts
  apps/webstore/src/app/shared/components/products/quotable-design/quotable-design.component.spec.ts
  apps/webstore/src/app/shared/components/products/quotable-design/quotable-design.component.ts
  apps/webstore/src/app/shared/services/authentication/auth.service.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.ts
  apps/webstore/src/app/shared/services/errorlog/errorlog.service.ts
  apps/webstore/src/app/shared/services/user/user.service.ts
  libs/interfaces/src/lib/errorlog/errorlog-priority.enum.ts
  libs/interfaces/src/lib/errorlog/errorlog.interace.ts
  libs/interfaces/src/lib/errorlog/index.ts
  libs/interfaces/src/lib/index.ts
  libs/models/src/lib/local-storage/local-storage.constants.ts
Labels: feat 🎸

#345 feat: TC-160 Add user event logs
  apps/admin-page-e2e/src/integration/app.spec.ts
  apps/admin-page/src/app/app-routing.module.ts
  apps/admin-page/src/app/app.component.html
  apps/admin-page/src/app/app.module.ts
  apps/admin-page/src/app/pages/events/events.component.css
  apps/admin-page/src/app/pages/events/events.component.html
  apps/admin-page/src/app/pages/events/events.component.ts
  apps/admin-page/src/app/services/events/events.service.ts
  apps/api/src/main/java/dk/treecreate/api/authentication/services/AuthUserService.java
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/events/Event.java
  apps/api/src/main/java/dk/treecreate/api/events/EventController.java
  apps/api/src/main/java/dk/treecreate/api/events/EventRepository.java
  apps/api/src/main/java/dk/treecreate/api/events/EventService.java
  apps/api/src/main/java/dk/treecreate/api/events/dto/CreateEventRequest.java
  apps/api/src/main/java/dk/treecreate/api/events/dto/GetEventsResponse.java
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.spec.ts
  apps/webstore/src/app/pages/issues/rejected-cookies/rejected-cookies.component.ts
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.spec.ts
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.ts
  apps/webstore/src/app/pages/payment-success/payment-success.component.ts
  apps/webstore/src/app/pages/products/product-pages/custom-order/custom-order.component.ts
  apps/webstore/src/app/pages/products/products-items.constant.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.ts
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/newsletter-signup-modal/newsletter-signup-modal.component.html
  apps/webstore/src/app/shared/components/modals/newsletter-signup-modal/newsletter-signup-modal.component.ts
  apps/webstore/src/app/shared/components/modals/quotable-template-modal/quotable-template-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/quotable-template-modal/quotable-template-modal.component.ts
  apps/webstore/src/app/shared/services/events/events.service.ts
  libs/interfaces/src/lib/events/event.interface.ts
  libs/interfaces/src/lib/events/index.ts
  libs/interfaces/src/lib/index.ts
Labels: feat 🎸

#350 Refactor/remove extra console logs
  apps/admin-page-e2e/src/integration/pages/order-details.spec.ts
  apps/admin-page-e2e/src/integration/pages/orders.spec.ts
  apps/admin-page/src/app/components/view-user-orders-dialog/view-user-orders-dialog.component.ts
  apps/admin-page/src/app/pages/account/account.component.ts
  apps/admin-page/src/app/pages/newsletters/newsletters.component.ts
  apps/admin-page/src/app/pages/order-details/order-details.component.ts
  apps/webstore-e2e/src/integration/components/modals/go-to-basket-modal.spec.ts
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.ts
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.ts
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.spec.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.ts
  libs/interfaces/src/lib/design/quotable/quotable.interface.ts
Labels: refactor 💡

#353 fix: 🐛 Fix event log failing when not logged in
  apps/webstore/src/app/shared/services/events/events.service.ts
Labels: fix 🐛

#354 Feat/add extra event logs
  apps/admin-page/src/app/pages/edit-discount/edit-discount.component.ts
  apps/webstore-e2e/src/integration/components/modals/add-to-basket-modal.spec.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/app/pages/auth/login/login.component.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.ts
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.ts
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.ts
  apps/webstore/src/app/shared/components/items/collection-item/collection-item.component.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.ts
  apps/webstore/src/app/shared/components/modals/privacy-notice-modal/privacy-notice-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/privacy-notice-modal/privacy-notice-modal.component.ts
  apps/webstore/src/app/shared/components/modals/terms-of-sale-modal/terms-of-sale-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/terms-of-sale-modal/terms-of-sale-modal.component.ts
  apps/webstore/src/app/shared/components/modals/terms-of-use-modal/terms-of-use-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/terms-of-use-modal/terms-of-use-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
Labels: feat 🎸

#356 chore: 🤖 Make nx-springboot package a prod dependency
  package.json
Labels: fix 🐛

#357 style: 💄 Add extra margin to cookie prompt on mobile
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.css
Labels: style 💄

#352 test:/# TC-159 Refactor Price calculation logic
  apps/api/src/test/java/dk/treecreate/api/order/OrderServiceTest.java
  apps/webstore/src/app/app.component.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.spec.ts
  apps/webstore/src/app/pages/auth/checkout/checkout.component.spec.ts
  apps/webstore/src/app/pages/auth/collection/collection.component.spec.ts
  apps/webstore/src/app/pages/auth/login/login.component.spec.ts
  apps/webstore/src/app/pages/auth/orders/orders.component.spec.ts
  apps/webstore/src/app/pages/auth/profile/profile.component.spec.ts
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.spec.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.spec.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.spec.ts
  apps/webstore/src/app/pages/home/home.component.spec.ts
  apps/webstore/src/app/pages/issues/page-not-found/page-not-found.component.spec.ts
  apps/webstore/src/app/pages/payment-cancelled/payment-cancelled.component.spec.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.spec.ts
  apps/webstore/src/app/pages/products/product-pages/quotable/quotable.component.spec.ts
  apps/webstore/src/app/pages/products/products.component.spec.ts
  apps/webstore/src/app/shared/components/footer/footer.component.spec.ts
  apps/webstore/src/app/shared/components/items/basket-item/basket-item.component.spec.ts
  apps/webstore/src/app/shared/components/items/custom-order-display/custom-order-display.component.spec.ts
  apps/webstore/src/app/shared/components/items/product-display/product-display.component.spec.ts
  apps/webstore/src/app/shared/components/modals/add-to-basket-modal/add-to-basket-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/cookie-prompt-modal/cookie-prompt-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/family-tree-intro-modal/family-tree-intro-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/family-tree-template-modal/family-tree-template-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/forgot-password-modal/forgot-password-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/go-to-basket-modal/go-to-basket-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/newsletter-signup-modal/newsletter-signup-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/privacy-notice-modal/privacy-notice-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/quotable-template-modal/quotable-template-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/terms-of-sale-modal/terms-of-sale-modal.component.spec.ts
  apps/webstore/src/app/shared/components/modals/terms-of-use-modal/terms-of-use-modal.component.spec.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.spec.ts
  apps/webstore/src/app/shared/components/products/family-tree/draggable-box/draggable-box.component.spec.ts
  apps/webstore/src/app/shared/components/products/family-tree/family-tree-design/family-tree-design.component.spec.ts
  apps/webstore/src/app/shared/components/products/quotable-design/quotable-design.component.spec.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.spec.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.spec.ts
  apps/webstore/src/app/shared/services/calculate-price/calculate-price.service.ts
  apps/webstore/src/app/shared/services/calculate-price/test-data.constant.ts
Labels: refactor 💡

#358 Chore/#tc 172 ssr for better seo
  .deploy/.env-files/.env.dev.frontend.example
  .deploy/webstore/Dockerfile
  .deploy/webstore/nginx.conf
  apps/admin-page/src/robots.txt
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/index.html
  apps/webstore/src/index.prod.html
  apps/webstore/src/robots.txt
  workspace.json
Labels: feat 🎸, chore 🤖

#359 Chore/#tc 184 log api traffic
  apps/api/src/main/java/dk/treecreate/api/config/RequestLoggingFilterConfig.java
  apps/api/src/main/resources/application.properties
Labels: chore 🤖

#360 Feat/#tc 131 create discount for newsletter email
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountController.java
  apps/api/src/main/java/dk/treecreate/api/discount/DiscountService.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/NewsletterController.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/NewsletterService.java
  apps/api/src/main/java/dk/treecreate/api/utils/StringService.java
  apps/api/src/main/resources/messages.properties
  apps/api/src/main/resources/messages_dk.properties
  apps/api/src/main/resources/templates/emails/newsletter-discount.html
  apps/api/src/test/java/dk/treecreate/api/newsletter/NewsletterControllerTests.java
Labels: feat 🎸

#364 Refactor/#TC-173 Change locale DK to DA for better SEO
  .deploy/.env-files/.env.dev.frontend.example
  .deploy/.env-files/.env.prod.frontend.example
  .deploy/webstore/Dockerfile
  .deploy/webstore/nginx.conf
  apps/api/src/main/java/dk/treecreate/api/authentication/AuthController.java
  apps/api/src/main/java/dk/treecreate/api/config/LocaleConfig.java
  apps/api/src/main/java/dk/treecreate/api/mail/MailService.java
  apps/api/src/main/java/dk/treecreate/api/newsletter/NewsletterController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/user/UserController.java
  apps/api/src/main/java/dk/treecreate/api/utils/LinkService.java
  apps/api/src/main/java/dk/treecreate/api/utils/LocaleService.java
  apps/api/src/main/java/dk/treecreate/api/utils/QuickpayService.java
  apps/api/src/main/resources/messages_da.properties
  apps/api/src/test/java/dk/treecreate/api/authentication/AuthControllerTests.java
  apps/api/src/test/java/dk/treecreate/api/utils/LinkServiceTest.java
  apps/api/src/test/java/dk/treecreate/api/utils/LocaleServiceTest.java
  apps/webstore-e2e/src/integration/components/modals/newsletter-popup-modal.spec.ts
  apps/webstore-e2e/src/integration/pages/auth/signup.spec.ts
  apps/webstore-e2e/src/integration/services/localization/localization.spec.ts
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/pages/auth/unsubscribe/unsubscribe.component.ts
  apps/webstore/src/app/pages/products/product-pages/family-tree/family-tree.component.ts
  apps/webstore/src/app/shared/components/footer/footer.component.ts
  apps/webstore/src/app/shared/components/modals/newsletter-signup-modal/newsletter-signup-modal.component.ts
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.ts
  apps/webstore/src/app/shared/components/review-carousel/review-carousel.component.html
  apps/webstore/src/app/shared/services/authentication/auth.service.ts
  apps/webstore/src/app/shared/services/newsletter/newsletter.service.ts
  apps/webstore/src/app/shared/services/order/newsletter/newsletter.service.spec.ts
  apps/webstore/src/app/shared/services/order/newsletter/newsletter.service.ts
  apps/webstore/src/app/shared/services/order/order.service.ts
  apps/webstore/src/app/shared/services/user/user.service.ts
  apps/webstore/src/environments/environment.da.ts
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/index.prod.html
  docs/i18n-localization-guide.md
  docs/swagger-ui.md
  libs/local-storage/src/lib/local-storage.service.ts
  libs/models/src/lib/local-storage/locale.constants.ts
  package.json
  workspace.json
Labels: refactor 💡
