Repository treecreate/webstore, pull requests merged in 2022-09, with the labels that each got.

#369 Refactor/#tc 220 adjust page not found url
  apps/webstore-e2e/src/integration/pages/page-not-found.spec.ts
  apps/webstore-e2e/src/integration/services/localization/localization.spec.ts
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.component.ts
Labels: refactor 💡

#372 Fix/fix issues with locale url
  apps/webstore/src/app/app.component.ts
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
Labels: fix 🐛

#374 Fix/add sitemap to webstore build files
  apps/webstore/src/sitemap.xml
  workspace.json
Labels: fix 🐛

#377 feat/#225 upgrade setting password
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.css
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.html
  apps/webstore/src/app/pages/auth/reset-password/reset-password.component.ts
  apps/webstore/src/app/pages/auth/signup/signup.component.css
  apps/webstore/src/app/pages/auth/signup/signup.component.html
  apps/webstore/src/app/pages/auth/signup/signup.component.ts
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.css
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.html
  apps/webstore/src/app/shared/components/modals/change-password-modal/change-password-modal.component.ts
  apps/webstore/src/app/shared/components/sticky-newsletter-button/sticky-newsletter-button.component.html
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
Labels: feat 🎸

#383 Feat/#233 remove trustpilot widget
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/assets/logos/soMe/trustpilot-21.png
  apps/webstore/src/index.html
Labels: feat 🎸

#381 Feat/#235 add input check before payment
  apps/webstore-e2e/src/integration/pages/auth/checkout.spec.ts
  apps/webstore/src/app/pages/auth/basket/basket.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.css
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
  package-lock.json
  package.json
Labels: feat 🎸

#385 Feat/#174 add planted trees endpoint
  apps/api/src/main/java/dk/treecreate/api/config/WebSecurityConfig.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderController.java
  apps/api/src/main/java/dk/treecreate/api/order/OrderRepository.java
  apps/api/src/main/java/dk/treecreate/api/order/dto/GetPlantedTreesResponse.java
  apps/api/src/test/java/dk/treecreate/api/order/OrderControllerTests.java
Labels: feat 🎸

#388 Feat/#227 loading screen after pressing payment
  apps/webstore/src/app/pages/auth/checkout/checkout.component.css
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
Labels: feat 🎸

#386 Feat/#153 create about us page
  apps/webstore/src/app/app-routing.module.ts
  apps/webstore/src/app/app.module.ts
  apps/webstore/src/app/pages/about-us/about-us.component.css
  apps/webstore/src/app/pages/about-us/about-us.component.html
  apps/webstore/src/app/pages/about-us/about-us.component.ts
  apps/webstore/src/app/pages/about-us/about-us.mobile.component.scss
  apps/webstore/src/app/pages/home/home.component.css
  apps/webstore/src/app/pages/home/home.component.html
  apps/webstore/src/app/shared/components/navbar/navbar.component.html
  apps/webstore/src/app/shared/services/order/order.service.ts
  apps/webstore/src/assets/img/about-us/2-year-icon.svg
  apps/webstore/src/assets/img/about-us/baby-photo.png
  apps/webstore/src/assets/img/about-us/background.svg
  apps/webstore/src/assets/img/about-us/family-photo.png
  apps/webstore/src/assets/img/about-us/grandmother-photo.png
  apps/webstore/src/assets/img/about-us/heart-icon.svg
  apps/webstore/src/assets/logos/soMe/pinterest.svg
  apps/webstore/src/assets/logos/soMe/tiktok.svg
  apps/webstore/src/i18n/messages.da.xlf
  apps/webstore/src/i18n/messages.xlf
Labels: feat 🎸

#390 Feat/#239 fix error messages in checkout
  apps/webstore/src/app/pages/auth/checkout/checkout.component.html
  apps/webstore/src/app/pages/auth/checkout/checkout.component.ts
Labels: feat 🎸

#392 Feat/#137 discount page update
  apps/admin-page/src/app/pages/discounts/discounts.component.html
  apps/admin-page/src/app/pages/discounts/discounts.component.ts
  package-lock.json
Labels: feat 🎸
